### ISSUE TITLE
Support for Shader RGB Node

### ISSUE THREAD

**Issue by don1138** [don1138/blender-qmc#1]
![Snipaste_2022-10-18_10-48-55](https://user-images.githubusercontent.com/107256886/196324635-8e57d38f-c88d-4fd7-93a1-cb0ac4ab8cc8.png)
Sorry, I don't know how to put requirements under your qmc plugin. Can you add an RGB node instead of modifying the BSDF Shader, because in actual work, many copied materials do not contain the BSDF Shader

**Comment by don1138** [comment]
Adding a **Shader RGB** node is outside the scope of this add-on, but I've added it to the type of nodes affected by the **Selected Nodes** checkbox.

[Version 1.2.2](https://github.com/don1138/blender-qmc/releases/tag/v1.2.2) has been posted to **Releases**.

You have to `Add > Input > RGB` manually, but once the node exists, if you select it and make sure **Selected Nodes** is checked, the add-on will now set its color.

*BTW -- I'm glad to hear you find my add-ons useful. I would love to see how you are using them and what you are making with them.*

**Comment by chenpaner** [comment]
Haha, actually saw you updated to version 1.2.2 right after I asked the question, I've tried it, it works, it's already perfect!

I'm an industrial designer and I mainly use blender to render product renderings. I used keyshot before, but I've switched to blender now. Here are some of my rendering exercises
https://www.behance.net/chenpaner

**Comment by don1138** [comment]
Nice stuff on your Behance! I like the bump texture you have on that Playstation controller.

If you have any other suggestions for the add-ons, I'd be glad to hear them.
